upstream:
  backstage:
    image:
      registry: quay.io
      repository: rhdh-community/rhdh
      tag: pr-2796
      pullPolicy: IfNotPresent

    appConfig:
      # backend:
      #   csp:
      #     img-src:
      #       # "'self'" and 'data' are from the backstage default but must be set since img-src is overwritten
      #       - "'self'"
      #       - 'data:'
      #       - https://avatars.githubusercontent.com

      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]

      permission:
        enabled: true
        rbac:
          pluginsWithPermission:
            - catalog
            - permission
            - scaffolder
          # policyFileReload: true
          # policies-csv-file: ./rbac/rbac-policies.csv
          # conditionalPoliciesFile: ./rbac-conditions/rbac-conditional-policies.yaml
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov
            users:
              - name: user:default/rhdh-qe

  # reduce memory usage
  postgresql:
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
