apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: christoph-demo3-service
  title: Christophs Demo 3 Service
  description: |
    This is a small demo service with annotations for:
    - Tekton (with namespace and label selector)
  links:
    - title: My RHDH notes
      url: https://github.com/christoph-jerolimov/rhdh-experiments
  annotations:
    backstage.io/source-location: url:https://github.com/christoph-jerolimov/rhdh-experiments/blob/main/test-catalog/components/christoph-demo1-service.yaml
    backstage.io/techdocs-ref: dir:../../../techdocs/christoph-demo
    github.com/project-slug: christoph-jerolimov/rhdh-experiments
    backstage.io/kubernetes-id: christoph-demo3-service
    backstage.io/kubernetes-namespace: christoph
    backstage.io/kubernetes-label-selector: component=christoph-demo3-service
    tekton.dev/cicd: "true"
  tags:
    - christoph-demo
spec:
  type: service
  owner: user:cjerolim
  lifecycle: experimental
  system: christoph-demo-system
  subcomponentOf: christoph-demo2-service
