apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: christoph-demo2-service
  title: Christophs Demo 2 Service
  description: |
    This is a small demo service with annotations for:
    - Tekton (without namespace filter)
  links:
    - title: My RHDH notes
      url: https://github.com/christoph-jerolimov/rhdh-experiments
  annotations:
    backstage.io/source-location: url:https://github.com/christoph-jerolimov/rhdh-experiments/blob/main/test-catalog/components/christoph-demo2-service.yaml
    backstage.io/techdocs-entity: system:christoph-demo-system
    github.com/project-slug: christoph-jerolimov/rhdh-experiments
    backstage.io/kubernetes-id: christoph-demo2-service
    #backstage.io/kubernetes-namespace: christoph-backstage-test
    tekton.dev/cicd: "true"
  tags:
    - christoph-demo
spec:
  type: service
  owner: user:cjerolim
  lifecycle: experimental
  system: christoph-demo-system
  subcomponentOf: christoph-demo1-service
