upstream:
  backstage:
    image:
      registry: registry.redhat.io
      repository: rhdh/rhdh-hub-rhel9
      tag: '1.3'
      pullPolicy: Always
    appConfig:
      app:
        branding:
          # https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/getting_started_with_red_hat_developer_hub/assembly-customize-rhdh-theme#proc-customize-rhdh-branding_assembly-customize-rhdh-theme
          theme:
            light:
              palette:
                primary:
                  main: '#00ff00'
                navigation:
                  indicator: '#00ffff'
              pageTheme:
                default:
                  backgroundColor: ['#00ff00', '#0000ff']
            dark:
              palette:
                primary:
                  main: '#00ff00'
                navigation:
                  indicator: '#00ffff'
              pageTheme:
                default:
                  backgroundColor: ['#00ff00', '#0000ff']
      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]
