global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar
        disabled: false
upstream:
  backstage:
    image:
      registry: quay.io
      repository: janus-idp/backstage-showcase
      tag: next
      pullPolicy: Always
