global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-http-request-dynamic
        disabled: false

upstream:
  backstage:
    image:
      registry: registry.redhat.io
      repository: rhdh/rhdh-hub-rhel9
      tag: '1.3'
      pullPolicy: Always
    appConfig:
      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]

      permission:
        enabled: true
        rbac:
          pluginsWithPermission:
            - bulk-import
            - catalog
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov
