apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ciiay
  title: Yi Cai (GitHub) # shown in the table
spec:
  profile:
    displayName: Yi Cai (GitHub) # shown on the detail page
    picture: https://avatars.githubusercontent.com/u/26255262?v=4
  memberOf: [rhdh-team]
