global:
  dynamic:
    plugins:
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
      #   disabled: false
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import
        disabled: false
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic
        disabled: false
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-topology
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-acr
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-jfrog-artifactory
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-nexus-repository-manager
      #   disabled: false
      # - package: ./dynamic-plugins/dist/backstage-community-plugin-quay
      #   disabled: false

      # test scorecard plugin
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard:next__0.1.0!red-hat-developer-hub-backstage-plugin-scorecard
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub-backstage-plugin-scorecard:
                entityTabs:
                  - mountPoint: entity.page.scorecard
                    path: /scorecard
                    title: Scorecard
                    titleKey: entityTab.title # does not exist yet
                    # config:
                    #   if:
                    #     allOf:
                    #       - isBookmarksAvailable
                mountPoints:
                  - mountPoint: entity.page.scorecard/cards
                    importName: EntityScorecardContent
                    config:
                      layout:
                        gridColumn: 1 / -1

      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend:next__0.1.0!red-hat-developer-hub-backstage-plugin-scorecard-backend
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-github:next__0.1.0!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-github
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-jira:next__0.1.0!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-jira
        pluginConfig:
          proxy:
            '/jira/api':
              target: https://redhat-team-f703ynt3.atlassian.net
              headers:
                Authorization: 'Basic Y2plcm9saW1AcmVkaGF0LmNvbTpBVEFUVDN4RmZHRjBwRG1IV3dQQm5JMlpuNzBWY3B5dkFPRGg2WGx5ZjJWLS1KQzNwM0VZUkx6Z3hPUlZRQlF2U05UdFY0MXlLMUt6YWlnei1URjJ6REV5d25ZRmFNa3hLQUFuZERxUUE4RWNiQWZXbmZPeS12bGZFazVpV3Nxc18zRDFQZUtGb2VabXpkVDg3YjFpZDBCT0Z4RG9XYzZKYV9VeHZYY0V2aTZqTFZyaFQ5M0UteGs9M0UzN0U2M0I='
                Accept: 'application/json'
                Content-Type: 'application/json'
                X-Atlassian-Token: 'nocheck'
                User-Agent: RHDH

          jira:
            proxyPath: /jira/api
            product: cloud
            baseUrl: https://redhat-team-f703ynt3.atlassian.net
            token: 'Y2plcm9saW1AcmVkaGF0LmNvbTpBVEFUVDN4RmZHRjBwRG1IV3dQQm5JMlpuNzBWY3B5dkFPRGg2WGx5ZjJWLS1KQzNwM0VZUkx6Z3hPUlZRQlF2U05UdFY0MXlLMUt6YWlnei1URjJ6REV5d25ZRmFNa3hLQUFuZERxUUE4RWNiQWZXbmZPeS12bGZFazVpV3Nxc18zRDFQZUtGb2VabXpkVDg3YjFpZDBCT0Z4RG9XYzZKYV9VeHZYY0V2aTZqTFZyaFQ5M0UteGs9M0UzN0U2M0I='

      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-jira
        disabled: true
      - package:  ./dynamic-plugins/dist/backstage-community-plugin-github-issues
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-github-pull-requests
        disabled: false

      # test config viewer
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/proberaum-backstage-plugin-config-viewer:next__0.4.1!proberaum-backstage-plugin-config-viewer
        pluginConfig:
          dynamicPlugins:
            frontend:
              proberaum.backstage-plugin-config-viewer:
                translationResources:
                  - importName: configViewerTranslations
                    ref: configViewerTranslationRef
                dynamicRoutes:
                  - path: /config-viewer
                    importName: ConfigViewerPage
                    menuItem:
                      text: Config viewer (from yaml)

upstream:
  backstage:
    image:
      registry: quay.io
      repository: rhdh-community/rhdh
      tag: next
      pullPolicy: IfNotPresent

    appConfig:
      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]

          # test scorecard plugin
          - type: url
            target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/scorecard/examples/all-scorecards.yaml
          - type: url
            target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/scorecard/examples/github-scorecard-only.yaml
          - type: url
            target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/scorecard/examples/jira-scorecard-only.yaml
          - type: url
            target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/scorecard/examples/no-scorecards.yaml

          # test npm plugin
          - type: url
            target: https://github.com/backstage/community-plugins/blob/main/workspaces/npm/examples/npmjs-examples.yaml
          - type: url
            target: https://github.com/backstage/community-plugins/blob/main/workspaces/npm/examples/github-examples.yaml
          - type: url
            target: https://github.com/backstage/community-plugins/blob/main/workspaces/npm/examples/gitlab-examples.yaml

      dynamicPlugins:
        frontend:
          default.main-menu-items:
            menuItems:
              default.home:
                title: Home (changed)

      i18n:
        locales:
          - en
          - de
          - fr
          - it

      permission:
        enabled: false
        rbac:
          pluginsWithPermission:
            - catalog
            - permission
            - scaffolder
          # policyFileReload: true
          # policies-csv-file: ./rbac/rbac-policies.csv
          # conditionalPoliciesFile: ./rbac-conditions/rbac-conditional-policies.yaml
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov
            users:
              - name: user:default/rhdh-qe

  # reduce memory usage
  postgresql:
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
