global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import-backend-dynamic
        disabled: false

upstream:
  backstage:
    image:
      registry: registry.redhat.io
      repository: rhdh/rhdh-hub-rhel9
      tag: '1.3'
      pullPolicy: IfNotPresent
    appConfig:
      app:
        # branding:
        #   theme:
        #     light:
        #       palette:
        #         primary:
        #           main: '#00ff00'
        #         navigation:
        #           indicator: '#00ffff'
        #       pageTheme:
        #         default:
        #           backgroundColor: ['#00ff00', '#0000ff']
        #     dark:
        #       palette:
        #         primary:
        #           main: '#00ff00'
        #         navigation:
        #           indicator: '#00ffff'
        #       pageTheme:
        #         default:
        #           backgroundColor: ['#00ff00', '#0000ff']
      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]

      permission:
        enabled: true
        rbac:
          pluginsWithPermission:
            - bulk-import
            - catalog
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov
