global:
  dynamic:
    plugins:

      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-floating-action-button
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-global-floating-action-button:
                mountPoints:
                  - mountPoint: application/listener
                    importName: DynamicGlobalFloatingActionButton

                  - mountPoint: global.floatingactionbutton/component
                    importName: NullComponent
                    config:
                      icon: github
                      label: GitHub
                      toolTip: GitHub
                      to: https://github.com/redhat-developer/rhdh
                  - mountPoint: global.floatingactionbutton/component
                    importName: NullComponent
                    config:
                      label: RHDH
                      toolTip: RHDH
                      to: https://developers.redhat.com/rhdh/overview

      - package: '@red-hat-developer-hub/backstage-plugin-application-provider-test@0.0.2'
        integrity: 'sha512-N3HxvTNe/CxTDtXIsvfre3ZoFLWYfPxz/IJiKY3nzA5C0wcH4lZn+fI+mDFoTUXogt7fZWyl3mCrdwQWrOEM8A=='
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-application-provider-test:
                dynamicRoutes:
                  - path: /application-provider-test-page
                    importName: TestPage
                mountPoints:
                  # - mountPoint: application/provider
                  #   importName: CrashProvider
                  - mountPoint: application/provider
                    importName: TestProviderOne
                  - mountPoint: application/provider
                    importName: TestProviderTwo

      - package: '@red-hat-developer-hub/backstage-plugin-application-listener-test@0.0.2'
        integrity: 'sha512-GRLbpjXE9ZyfRJr/iyp+1L2sUQL97aPc+FV/IORH63eGT32Uc0xCFBu51fGPYJFmXY49BlSh+CnVnbKNsyiOAQ=='
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-application-listener-test:
                dynamicRoutes:
                  - path: /application-provider-test-page
                    importName: TestPage
                mountPoints:
                  # - mountPoint: application/listener
                  #   importName: CrashListener
                  - mountPoint: application/listener
                    importName: LocationListener

upstream:
  backstage:
    image:
      registry: quay.io
      repository: rhdh-community/rhdh
      tag: pr-2199
      pullPolicy: IfNotPresent

    appConfig:
      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]

          - type: url
            target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/marketplace/examples/all-orgs.yaml
            rules:
              - allow: [Group]
          - type: url
            target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/marketplace/examples/all-plugins.yaml
            rules:
              - allow: [Plugin]
          - type: url
            target: https://github.com/redhat-developer/rhdh-plugins/blob/main/workspaces/marketplace/examples/all-pluginlists.yaml
            rules:
              - allow: [PluginList]

      dynamicPlugins:
        frontend:
          default.main-menu-items:
            menuItems:
              default.home:
                title: Home (changed)

      permission:
        enabled: true
        rbac:
          pluginsWithPermission:
            - catalog
            - permission
            - scaffolder
          # policyFileReload: true
          # policies-csv-file: ./rbac/rbac-policies.csv
          # conditionalPoliciesFile: ./rbac-conditions/rbac-conditional-policies.yaml
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov
            users:
              - name: user:default/rhdh-qe

  # reduce memory usage
  postgresql:
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
