apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: HTTP-testing
  title: Http testing for post/get
  description: Testing get functionality with get
spec:
  type: service

  parameters:
    - title: Fill in some steps
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:disabled: true

  steps:
    - id: request1
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/httpbin/delay/10'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: request2
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/httpbin/delay/10'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: request3
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/httpbin/delay/10'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: request4
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/httpbin/delay/10'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: request5
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/httpbin/delay/10'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: request6
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/httpbin/delay/10'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: request7
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/httpbin/delay/10'
        headers:
          test: 'hello'
          foo: 'bar'

    - id: log-response
      name: Log response
      action: debug:log
      input:
        message: |
          **Status code:**
          ${{ steps.request1.output.code }}

          **Status code:**
          ${{ steps.request2.output.code }}

          **Status code:**
          ${{ steps.request3.output.code }}

          **Status code:**
          ${{ steps.request4.output.code }}

          **Status code:**
          ${{ steps.request5.output.code }}

          **Status code:**
          ${{ steps.request6.output.code }}

          **Status code:**
          ${{ steps.request7.output.code }}

  output:
    text:
      - title: Response
        content: |
          **Status code:**
          ${{ steps.request1.output.code }}

          **Status code:**
          ${{ steps.request2.output.code }}

          **Status code:**
          ${{ steps.request3.output.code }}

          **Status code:**
          ${{ steps.request4.output.code }}

          **Status code:**
          ${{ steps.request5.output.code }}

          **Status code:**
          ${{ steps.request6.output.code }}

          **Status code:**
          ${{ steps.request7.output.code }}
