global:
  dynamic:
    plugins:
      - pamakeckage: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
        disabled: true

upstream:
  backstage:
    image:
      registry: quay.io
      repository: rhdh-community/rhdh
      tag: pr-2238-47fabd86
      pullPolicy: IfNotPresent

    appConfig:
      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]
          - type: url
            target: https://github.com/backstage/community-plugins/blob/main/workspaces/acr/examples/entities.yaml
            rules:
              - allow: [Component, System]

      dynamicPlugins:
        frontend:
          default.main-menu-items:
            menuItems:
              default.home:
                title: Home (changed)

          backstage.plugin-techdocs-module-addons-contrib:
            techdocsAddons:
              - importName: TextSize
              - importName: LightBox
              - importName: ReportIssue
              - importName: ExpandableNavigation

      permission:
        enabled: true
        rbac:
          pluginsWithPermission:
            - catalog
            - permission
            - scaffolder
          # policyFileReload: true
          # policies-csv-file: ./rbac/rbac-policies.csv
          # conditionalPoliciesFile: ./rbac-conditions/rbac-conditional-policies.yaml
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov
            users:
              - name: user:default/rhdh-qe

  # reduce memory usage
  postgresql:
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
